config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :customers 
  resources :banks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
    has_many :credit_cards
    has_many :customers, through: :credit_cards

    def info
        self.name + " " + self.city
    end
    
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
    belongs_to :customer
    belongs_to :bank
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :credit_cards
    has_many :banks, through: :credit_cards

    def info
        "Customer Name: #{self.name}, Age: #{self.age.to_s}"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController

    def index
        @banks = Bank.all
    end

    def show
        bank_finder
    end

    def new
        @bank = Bank.new
    end

    def create    
        @bank = Bank.new(strong_params)
        @bank.save
        redirect_to bank_path(@bank)
    end
    
    def edit        
        bank_finder
    end
    
    def update
        bank_finder
        @bank.update(strong_params)
        redirect_to bank_path(@bank)
    end
    
    def destroy
        bank_finder
        @bank.delete
        redirect_to banks_path
    end

    private

    def strong_params
        params.require(:bank).permit(:name, :city)
    end

    def bank_finder
        @bank = Bank.find(params[:id])
    end
    
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

    def index
        @customers = Customer.all
    end

    def show
        customer_finder
    end

    def create  
        byebug
        @customer = Customer.new(strong_params)
        @customer.save
        redirect_to customer_path(@customer)
    end

    def new
        @customer = Customer.new
    end
    
    def edit        
        customer_finder
    end
    
    def update
        customer_finder
        @customer.update(strong_params)
        redirect_to customer_path(@customer.id)
    end

    def destroy
        customer_finder
        @customer.delete
        redirect_to customers_path
    end

    private

    def strong_params
        params.require(:customer).permit(:name, :age)
    end

    def customer_finder
        @customer = Customer.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/banks/edit.html.erb
<%= form_for @bank do |f| %>
    <%= f.label :name, 'Bank Name' %><br>
    <%= f.text_field :name %><br>

    <%= f.label :city, 'Bank City' %><br>
    <%= f.text_field :city %><br>

    <%= f.submit 'Submit' %><br>
    <%end %>

app/views/banks/index.html.erb
<% @banks.each do |bank| %>
    <ul>
        <li><%= bank.info %></li>
        <%= link_to 'Click here for bank info', bank_path(bank)%><br>

        <%= link_to 'Destroy Bank Record', bank_path(bank), 
        method: :delete,
        data: { confirm: 'Do you wish to delete this bank record?' }%>
        <br>

    </ul>
<% end %>

app/views/banks/show.html.erb
<h2> Bank Name: </h2>
<%= @bank.name %><br>
<h2> City: </h2>
<%= @bank.city %>

app/views/customers/edit.html.erb
<%= form_for @customer do |f| %>
    <%= f.label :name, 'Customer Name' %><br>
    <%= f.text_field :name %><br>

    <%= f.label :age, 'Customer Age' %><br>
    <%= f.text_field :age %><br>

    <%= f.submit 'Submit' %><br>
    <%end %>

app/views/customers/index.html.erb
<h2> List of Customers</h2>

<%= link_to 'No profile? Click here to register', new_customer_path %>

<% @customers.each do |customer|%>
    <ul>
        <h3><li><%= link_to customer.name, customer_path(customer) %></li></h3>
        <h3> Bank Name: </h3>
        <% customer.banks.each do |bank| %>
            <%= bank.name %><br>
            <% end %>
   </ul>
<%end%>

app/views/customers/new.html.erb
<h3>Customer Form</h3>

<%= form_for @customer do |f| %>
    <%= f.label :name, 'Customer Name' %><br>
    <%= f.text_field :name %><br>

    <%= f.label :age, 'Customer Age' %><br>
    <%= f.text_field :age %><br>

    <%= f.select :credit_card_ids, options_from_collection_for_select(CreditCard.all, "id", "card_name") %><br>

    <%= f.submit 'Create New Customer' %><br>
    <%end %>


    

app/views/customers/show.html.erb
<h3>Customer Information Page</h3>
<%= @customer.info %><br>

<%= link_to 'Edit My Profile', edit_customer_path(@customer) %><br>

<%= link_to 'Take me back to the homepage!', customers_path%><br>

<%= link_to 'Destroy Customer Record', customer_path(@customer),
        method: :delete,
        data: { confirm: 'Are you sure you want to delete your profile?!?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerCreditCardBank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>